language: node_js
before_install:
- npm install -g grunt-cli
script:
- grunt --stack travis
email:
  on_failure: change
  on_success: never
matrix:
  include:
  - node_js: '5'
  - node_js: '4'
cache:
  directories:
  - node_modules

git:
  depth: 100
